# Generated by Django 2.1.4 on 2018-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='artwork')),
                ('title', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Painting'), (1, 'Étude'), (2, 'Sketch')], default=0)),
            ],
        ),
    ]
