# Generated by Django 2.1.5 on 2019-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    def use_id(apps, schema_editor):
        Artwork = apps.get_model('artwork', 'Artwork')
        for a in Artwork.objects.all():
            a.order = a.id
            a.save()

    dependencies = [
        ('artwork', '0002_auto_20190107_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(use_id, reverse_code=migrations.RunPython.noop)
    ]
